// Catalogo dei testi consultabili nel lettore interattivo (/patto-interattivo/).
// I 10 atti UE stanno a /patto-interattivo/<num>.html, le norme italiane a
// /patto-interattivo/<slug>/index.html (stessa struttura del bundle su
// sospermesso.it e studiolegaleoltre.org — vedi sites.json nel progetto sorgente).
module.exports = {
  // data dell'ultima verifica dei testi (EUR-Lex / Normattiva)
  aggiornamento: '10 luglio 2026',
  aggiornamento_en: '10 July 2026',
  aggiornamento_fr: '10 juillet 2026',

  ue: [
    {
      num: '1346',
      tipo: 'Direttiva',
      numero: 'UE 2024/1346',
      titolo: 'Direttiva accoglienza',
      desc: "Norme sull'accoglienza e sul trattenimento dei richiedenti protezione internazionale.",
      icon: '🏠',
      en: { tipo: 'Directive', numero: 'EU 2024/1346', titolo: 'Reception Conditions Directive', desc: 'Rules on the reception and detention of applicants for international protection.' },
      fr: { tipo: 'Directive', numero: 'UE 2024/1346', titolo: 'Directive relative aux conditions d\'accueil', desc: 'Règles relatives à l\'accueil et à la rétention des demandeurs de protection internationale.' },
    },
    {
      num: '1347',
      tipo: 'Regolamento',
      numero: 'UE 2024/1347',
      titolo: 'Regolamento qualifiche',
      desc: 'Criteri per il riconoscimento dello status di rifugiato e della protezione sussidiaria.',
      icon: '✅',
      en: { tipo: 'Regulation', numero: 'EU 2024/1347', titolo: 'Qualification Regulation', desc: 'Criteria for recognition as a refugee or as a person eligible for subsidiary protection.' },
      fr: { tipo: 'Règlement', numero: 'UE 2024/1347', titolo: 'Règlement Qualification', desc: 'Critères de reconnaissance du statut de réfugié et de la protection subsidiaire.' },
    },
    {
      num: '1348',
      tipo: 'Regolamento',
      numero: 'UE 2024/1348',
      titolo: 'Regolamento procedure',
      desc: 'Procedura comune europea per la protezione internazionale.',
      icon: '📋',
      en: { tipo: 'Regulation', numero: 'EU 2024/1348', titolo: 'Asylum Procedure Regulation', desc: 'Common European procedure for international protection.' },
      fr: { tipo: 'Règlement', numero: 'UE 2024/1348', titolo: 'Règlement sur la procédure d\'asile', desc: 'Procédure commune européenne en matière de protection internationale.' },
    },
    {
      num: '1349',
      tipo: 'Regolamento',
      numero: 'UE 2024/1349',
      titolo: 'Regolamento rimpatrio alla frontiera',
      desc: 'Procedure di rimpatrio applicabili alla frontiera.',
      icon: '↩️',
      en: { tipo: 'Regulation', numero: 'EU 2024/1349', titolo: 'Return Border Procedure Regulation', desc: 'Return procedures applicable at the border.' },
      fr: { tipo: 'Règlement', numero: 'UE 2024/1349', titolo: 'Règlement sur la procédure de retour à la frontière', desc: 'Procédures de retour applicables à la frontière.' },
    },
    {
      num: '1350',
      tipo: 'Regolamento',
      numero: 'UE 2024/1350',
      titolo: 'Regolamento reinsediamento',
      desc: "Quadro dell'Unione per il reinsediamento e l'ammissione umanitaria.",
      icon: '🤝',
      en: { tipo: 'Regulation', numero: 'EU 2024/1350', titolo: 'Union Resettlement Framework Regulation', desc: 'Union framework for resettlement and humanitarian admission.' },
      fr: { tipo: 'Règlement', numero: 'UE 2024/1350', titolo: 'Règlement sur le cadre de l\'Union pour la réinstallation', desc: 'Cadre de l\'Union pour la réinstallation et l\'admission humanitaire.' },
    },
    {
      num: '1351',
      tipo: 'Regolamento',
      numero: 'UE 2024/1351',
      titolo: 'Regolamento RAMM (Dublino)',
      desc: "Gestione dell'asilo e della migrazione: sostituisce il sistema di Dublino.",
      icon: '🗂️',
      en: { tipo: 'Regulation', numero: 'EU 2024/1351', titolo: 'Asylum and Migration Management Regulation (AMMR, Dublin)', desc: 'Management of asylum and migration: replaces the Dublin system.' },
      fr: { tipo: 'Règlement', numero: 'UE 2024/1351', titolo: 'Règlement RGAM (Dublin)', desc: 'Gestion de l\'asile et de la migration : remplace le système de Dublin.' },
    },
    {
      num: '1352',
      tipo: 'Regolamento',
      numero: 'UE 2024/1352',
      titolo: 'Modifiche ECRIS-TCN',
      desc: 'Modifiche al sistema europeo di informazione sui casellari giudiziari di cittadini di paesi terzi.',
      icon: '🗄️',
      en: { tipo: 'Regulation', numero: 'EU 2024/1352', titolo: 'ECRIS-TCN amendments', desc: 'Amendments to the European system for exchanging criminal records information on third-country nationals.' },
      fr: { tipo: 'Règlement', numero: 'UE 2024/1352', titolo: 'Modifications ECRIS-TCN', desc: 'Modifications du système européen d\'information sur les casiers judiciaires des ressortissants de pays tiers.' },
    },
    {
      num: '1356',
      tipo: 'Regolamento',
      numero: 'UE 2024/1356',
      titolo: 'Regolamento screening',
      desc: 'Accertamenti su cittadini di paesi terzi alle frontiere esterne.',
      icon: '🔍',
      en: { tipo: 'Regulation', numero: 'EU 2024/1356', titolo: 'Screening Regulation', desc: 'Screening of third-country nationals at the external borders.' },
      fr: { tipo: 'Règlement', numero: 'UE 2024/1356', titolo: 'Règlement sur le filtrage', desc: 'Filtrage des ressortissants de pays tiers aux frontières extérieures.' },
    },
    {
      num: '1358',
      tipo: 'Regolamento',
      numero: 'UE 2024/1358',
      titolo: 'Regolamento Eurodac',
      desc: 'Banca dati europea delle impronte digitali e dei dati biometrici.',
      icon: '🫆',
      en: { tipo: 'Regulation', numero: 'EU 2024/1358', titolo: 'Eurodac Regulation', desc: 'European database of fingerprints and biometric data.' },
      fr: { tipo: 'Règlement', numero: 'UE 2024/1358', titolo: 'Règlement Eurodac', desc: 'Base de données européenne des empreintes digitales et des données biométriques.' },
    },
    {
      num: '1359',
      tipo: 'Regolamento',
      numero: 'UE 2024/1359',
      titolo: 'Regolamento crisi e forza maggiore',
      desc: 'Situazioni di crisi, strumentalizzazione e forza maggiore in materia di migrazione e asilo.',
      icon: '🚨',
      en: { tipo: 'Regulation', numero: 'EU 2024/1359', titolo: 'Crisis and Force Majeure Regulation', desc: 'Situations of crisis, instrumentalisation and force majeure in the field of migration and asylum.' },
      fr: { tipo: 'Règlement', numero: 'UE 2024/1359', titolo: 'Règlement sur les situations de crise et de force majeure', desc: 'Situations de crise, d\'instrumentalisation et de force majeure dans le domaine de la migration et de l\'asile.' },
    },
  ],

  it: [
    // Il decreto di adeguamento: atto di novella (non consolidato), reso come testo
    // vigente interattivo; le sue modifiche si leggono evidenziate nei tre testi
    // coordinati qui sotto. Un eventuale campo `href` scavalcherebbe il percorso
    // /patto-interattivo/<slug>/ (serviva quando la card puntava alla scheda).
    {
      slug: 'dl-100-2026',
      titolo: 'D.L. 100/2026',
      sotto: 'Prima attuazione italiana del Patto UE su migrazione e asilo',
      coord: 'Testo vigente — convertito senza modificazioni dalla l. 145/2026; artt. 1, 2 e 16 modificati dal d.l. 144/2026',
      icon: '📜',
      en: { titolo: 'Decree-Law 100/2026', sotto: 'First Italian implementation of the EU Pact on Migration and Asylum', coord: 'Text in force — converted without amendments by Law 145/2026; Arts. 1, 2 and 16 amended by Decree-Law 144/2026' },
      fr: { titolo: 'Décret-loi 100/2026', sotto: 'Première mise en œuvre italienne du Pacte de l\'UE sur la migration et l\'asile', coord: 'Texte en vigueur — converti sans modification par la loi 145/2026 ; art. 1, 2 et 16 modifiés par le décret-loi 144/2026' },
    },
    // Decreto di novella anch'esso (tratta, dir. 2024/1712): modifica l'art. 18 T.U.,
    // l'art. 17 d.lgs. 142/2015 e l'art. 32 d.lgs. 25/2008, che lo mostrano articolo per articolo.
    {
      slug: 'dlgs-115-2026',
      titolo: 'D.Lgs. 115/2026',
      sotto: 'Tratta di esseri umani: attuazione della direttiva (UE) 2024/1712',
      coord: 'Testo vigente — modifica gli artt. 18 T.U. immigrazione, 17 d.lgs. 142/2015 e 32 d.lgs. 25/2008',
      icon: '🛡️',
      en: { titolo: 'Legislative Decree 115/2026', sotto: 'Trafficking in human beings: implementation of Directive (EU) 2024/1712', coord: 'Text in force — amends Art. 18 Consolidated Immigration Act, Art. 17 Leg. Decree 142/2015 and Art. 32 Leg. Decree 25/2008' },
      fr: { titolo: 'Décret législatif 115/2026', sotto: 'Traite des êtres humains : transposition de la directive (UE) 2024/1712', coord: 'Texte en vigueur — modifie l\'art. 18 du texte unique sur l\'immigration, l\'art. 17 du décret législatif 142/2015 et l\'art. 32 du décret législatif 25/2008' },
    },
    {
      slug: 'dlgs-25-2008',
      titolo: 'D.Lgs. 25/2008',
      sotto: 'Procedure per il riconoscimento della protezione internazionale',
      coord: 'Testo coordinato con il d.l. 100/2026 (art. 11) e d.lgs. 115/2026 — versione precedente e modifiche per articolo',
      icon: '⚖️',
      en: { titolo: 'Legislative Decree 25/2008', sotto: 'Procedures for the recognition of international protection', coord: 'Consolidated text with Decree-Law 100/2026 (Art. 11) and Legislative Decree 115/2026 — previous version and amendments, article by article' },
      fr: { titolo: 'Décret législatif 25/2008', sotto: 'Procédures de reconnaissance de la protection internationale', coord: 'Texte coordonné avec le décret-loi 100/2026 (art. 11) et le décret législatif 115/2026 — version précédente et modifications, article par article' },
    },
    {
      slug: 'dlgs-142-2015',
      titolo: 'D.Lgs. 142/2015',
      sotto: 'Accoglienza dei richiedenti protezione internazionale',
      coord: 'Testo coordinato con il d.l. 100/2026 (art. 10) e d.lgs. 115/2026 — versione precedente e modifiche per articolo',
      icon: '🏘️',
      en: { titolo: 'Legislative Decree 142/2015', sotto: 'Reception of applicants for international protection', coord: 'Consolidated text with Decree-Law 100/2026 (Art. 10) and Legislative Decree 115/2026 — previous version and amendments, article by article' },
      fr: { titolo: 'Décret législatif 142/2015', sotto: 'Accueil des demandeurs de protection internationale', coord: 'Texte coordonné avec le décret-loi 100/2026 (art. 10) et le décret législatif 115/2026 — version précédente et modifications, article par article' },
    },
    {
      slug: 'dlgs-286-1998',
      titolo: 'D.Lgs. 286/1998',
      sotto: "Testo unico dell'immigrazione",
      coord: 'Testo coordinato con il d.l. 100/2026 (art. 12) e d.lgs. 115/2026 — versione precedente e modifiche per articolo',
      icon: '📕',
      en: { titolo: 'Legislative Decree 286/1998', sotto: 'Consolidated Immigration Act', coord: 'Consolidated text with Decree-Law 100/2026 (Art. 12) and Legislative Decree 115/2026 — previous version and amendments, article by article' },
      fr: { titolo: 'Décret législatif 286/1998', sotto: 'Texte unique sur l\'immigration', coord: 'Texte coordonné avec le décret-loi 100/2026 (art. 12) et le décret législatif 115/2026 — version précédente et modifications, article par article' },
    },
    {
      slug: 'dlgs-251-2007',
      titolo: 'D.Lgs. 251/2007',
      sotto: 'Qualifiche: status di rifugiato e protezione sussidiaria',
      coord: 'Testo vigente con rinvii navigabili',
      icon: '📗',
      en: { titolo: 'Legislative Decree 251/2007', sotto: 'Qualification: refugee status and subsidiary protection', coord: 'Text in force with navigable cross-references' },
      fr: { titolo: 'Décret législatif 251/2007', sotto: 'Qualification : statut de réfugié et protection subsidiaire', coord: 'Texte en vigueur avec renvois navigables' },
    },
  ],
};
